apiVersion: v1
kind: ConfigMap
metadata:
  name: bahyway-config
  namespace: bahyway
data:
  POSTGRES_USER: "bahyway"
  POSTGRES_DB: "bahyway_db"
  DATABASE_URL: "postgresql://bahyway:bahyway_secure_password@postgres-service:5432/bahyway_db"
  REDIS_URL: "redis://redis-service:6379/0"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  APP_NAME: "BahyWay Platform"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "development"
